import { StyleSheet } from 'react-native';

import { Fonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F9F7FC',
  },
  container: {
    flex: 1,
  },
  loadingState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  successContent: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  successCard: {
    alignItems: 'center',
    borderRadius: 32,
    backgroundColor: 'white',
    paddingHorizontal: 24,
    paddingVertical: 36,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 4,
  },
  successIcon: {
    width: 76,
    height: 76,
    borderRadius: 38,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 22,
  },
  successTitle: {
    fontSize: 24,
    lineHeight: 32,
    fontFamily: Fonts.title,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 12,
    paddingBottom: 2,
  },
  successMessage: {
    fontSize: 14,
    lineHeight: 21,
    fontFamily: Fonts.body,
    color: '#64748B',
    textAlign: 'center',
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 100,
  },
  stepIntro: {
    marginBottom: 28,
  },
  stepEyebrow: {
    fontSize: 12,
    fontFamily: Fonts.title,
    fontWeight: '900',
    color: '#8257E5',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 8,
  },
  stepTitle: {
    fontSize: 26,
    fontFamily: Fonts.title,
    fontWeight: '900',
    marginBottom: 8,
  },
  stepDescription: {
    fontSize: 14,
    lineHeight: 21,
    fontFamily: Fonts.body,
    color: '#64748B',
  },
  sectionHeaderLabel: {
    fontSize: 12,
    fontFamily: Fonts.title,
    fontWeight: '900',
    color: '#AAB7C6',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 20,
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: 14,
    fontFamily: Fonts.title,
    fontWeight: '900',
    marginBottom: 16,
  },
  fieldHint: {
    fontSize: 12,
    fontFamily: Fonts.body,
    marginTop: -10,
    marginBottom: 12,
    color: '#7C8EA8',
  },
  fieldHintInline: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: Fonts.body,
    marginTop: 2,
  },
  labelSmall: {
    fontSize: 14,
    fontFamily: Fonts.title,
    fontWeight: '900',
    marginBottom: 10,
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 16,
    marginBottom: 32,
  },
  gridItem: {
    width: '30%',
    aspectRatio: 1,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    paddingVertical: 24,
  },
  gridItemSelected: {
    borderColor: 'transparent',
    backgroundColor: 'white',
  },
  gridItemUnselected: {
    borderColor: 'transparent',
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  gridIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  gridLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  gridLabel: {
    fontSize: 12,
    fontFamily: Fonts.title,
    fontWeight: '900',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 100,
    paddingHorizontal: 24,
    paddingVertical: 20,
    marginBottom: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  inputContainerSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  searchWrapper: {
    zIndex: 1000,
    position: 'relative',
  },
  dropdownContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  resultsList: {
    position: 'absolute',
    top: 60,
    left: 0,
    right: 0,
    backgroundColor: 'white',
    borderRadius: 24,
    maxHeight: 200,
    zIndex: 1001,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 10,
    paddingVertical: 8,
  },
  resultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#F0F0F0',
  },
  resultItemText: {
    fontSize: 14,
    fontFamily: Fonts.title,
    fontWeight: '600',
  },
  inputIcon: {
    marginRight: 12,
  },
  textInput: {
    flex: 1,
    fontSize: 16,
    fontFamily: Fonts.title,
    fontWeight: 'bold',
  },
  textInputSmall: {
    flex: 1,
    fontSize: 14,
    fontFamily: Fonts.title,
    fontWeight: 'bold',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  dropdownContainerSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  dropdownTextSmall: {
    flex: 1,
    fontSize: 14,
    fontFamily: Fonts.title,
    fontWeight: '900',
  },
  providerChips: {
    gap: 10,
    paddingRight: 24,
    paddingBottom: 14,
  },
  providerChip: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: 'white',
    paddingHorizontal: 14,
  },
  providerChipText: {
    fontSize: 12,
    fontFamily: Fonts.title,
    fontWeight: '900',
    color: '#64748B',
  },
  colorScroll: {
    gap: 12,
    paddingRight: 24,
  },
  colorItem: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 4,
    borderColor: 'transparent',
  },
  colorItemSelected: {
    borderColor: 'white',
  },
  colorRing: {
    position: 'absolute',
    top: -6,
    left: -6,
    right: -6,
    bottom: -6,
    borderRadius: 30,
    borderWidth: 2,
  },
  defaultCardInFold: {
    marginTop: 0,
    marginBottom: 20,
  },
  defaultCard: {
    minHeight: 82,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 28,
    backgroundColor: 'white',
    paddingHorizontal: 18,
    paddingVertical: 16,
    marginTop: -6,
    marginBottom: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  defaultIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F4F1FE',
    marginRight: 14,
  },
  defaultCopy: {
    flex: 1,
    minWidth: 0,
    paddingRight: 12,
  },
  defaultTitle: {
    fontSize: 14,
    fontFamily: Fonts.title,
    fontWeight: '900',
  },
  defaultDescription: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 17,
    fontFamily: Fonts.body,
    color: '#64748B',
  },
  defaultToggle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#CBD5E1',
    backgroundColor: 'white',
  },
  footer: {
    paddingVertical: 16,
    paddingHorizontal: 24,
    backgroundColor: '#F9F7FC',
  },
  footerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  successActions: {
    gap: 12,
  },
  fullWidthButton: {
    minHeight: 56,
    borderRadius: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingHorizontal: 18,
  },
  secondaryFullWidthButton: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: 'white',
  },
  secondaryFullWidthText: {
    fontSize: 15,
    fontFamily: Fonts.title,
    fontWeight: '900',
    color: '#8257E5',
  },
  successDefaultPill: {
    minHeight: 44,
    borderRadius: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#F4F1FE',
    paddingHorizontal: 16,
  },
  successDefaultText: {
    fontSize: 13,
    fontFamily: Fonts.title,
    fontWeight: '900',
    color: '#8257E5',
  },
  doneTextButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    borderRadius: 16,
    backgroundColor: '#FFEBEE',
    borderWidth: 1,
    borderColor: 'rgba(211, 47, 47, 0.12)',
    padding: 12,
    marginBottom: 12,
  },
  errorText: {
    flex: 1,
    color: '#D32F2F',
    fontFamily: Fonts.body,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
  },
  cancelButton: {
    paddingHorizontal: 24,
  },
  cancelText: {
    fontSize: 14,
    fontFamily: Fonts.title,
    fontWeight: '900',
    color: '#BDBDBD',
  },
  saveButton: {
    backgroundColor: '#90A4AE',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 32,
    paddingVertical: 20,
    borderRadius: 32,
    shadowColor: '#90A4AE',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  saveButtonText: {
    color: 'white',
    fontSize: 16,
    fontFamily: Fonts.title,
    fontWeight: '900',
    marginRight: 8,
  },
  modalContent: {
    backgroundColor: 'white',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingBottom: 40,
    maxHeight: '70%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 24,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#F0F0F0',
  },
  modalTitle: {
    fontSize: 16,
    fontFamily: Fonts.title,
    fontWeight: '900',
  },
  modalList: {
    paddingHorizontal: 24,
  },
  modalItem: {
    paddingVertical: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#F0F0F0',
  },
  modalItemText: {
    fontSize: 14,
    fontFamily: Fonts.title,
    fontWeight: '600',
  },
});
